//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18444.
// 
#pragma warning disable 1591

namespace WhizzHardBooks.R_WHB {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_WHBSoap", Namespace="http://localhost/WS_WHB")]
    public partial class WS_WHB : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback inscribirLibroOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback llenarConsultarLibrosOperationCompleted;
        
        private System.Threading.SendOrPostCallback llenarPrestarLibroOperationCompleted;
        
        private System.Threading.SendOrPostCallback llenarReporteOperationCompleted;
        
        private System.Threading.SendOrPostCallback librosPrestadosSinDevolverOperationCompleted;
        
        private System.Threading.SendOrPostCallback clienteExisteOperationCompleted;
        
        private System.Threading.SendOrPostCallback yaPrestoElLibroOperationCompleted;
        
        private System.Threading.SendOrPostCallback yaReservoElLibroOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarPrestamoOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarReservaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ejempleresDisponiblesOperationCompleted;
        
        private System.Threading.SendOrPostCallback devolverOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_WHB() {
            this.Url = global::WhizzHardBooks.Properties.Settings.Default.WhizzHardBooks_R_WHB_WS_WHB;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event inscribirLibroCompletedEventHandler inscribirLibroCompleted;
        
        /// <remarks/>
        public event registrarClienteCompletedEventHandler registrarClienteCompleted;
        
        /// <remarks/>
        public event llenarConsultarLibrosCompletedEventHandler llenarConsultarLibrosCompleted;
        
        /// <remarks/>
        public event llenarPrestarLibroCompletedEventHandler llenarPrestarLibroCompleted;
        
        /// <remarks/>
        public event llenarReporteCompletedEventHandler llenarReporteCompleted;
        
        /// <remarks/>
        public event librosPrestadosSinDevolverCompletedEventHandler librosPrestadosSinDevolverCompleted;
        
        /// <remarks/>
        public event clienteExisteCompletedEventHandler clienteExisteCompleted;
        
        /// <remarks/>
        public event yaPrestoElLibroCompletedEventHandler yaPrestoElLibroCompleted;
        
        /// <remarks/>
        public event yaReservoElLibroCompletedEventHandler yaReservoElLibroCompleted;
        
        /// <remarks/>
        public event guardarPrestamoCompletedEventHandler guardarPrestamoCompleted;
        
        /// <remarks/>
        public event guardarReservaCompletedEventHandler guardarReservaCompleted;
        
        /// <remarks/>
        public event ejempleresDisponiblesCompletedEventHandler ejempleresDisponiblesCompleted;
        
        /// <remarks/>
        public event devolverCompletedEventHandler devolverCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WS_WHB/HelloWorld", RequestNamespace="http://localhost/WS_WHB", ResponseNamespace="http://localhost/WS_WHB", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WS_WHB/inscribirLibro", RequestNamespace="http://localhost/WS_WHB", ResponseNamespace="http://localhost/WS_WHB", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool inscribirLibro(int id, string tit, int exi, int pag, string tem, string aut) {
            object[] results = this.Invoke("inscribirLibro", new object[] {
                        id,
                        tit,
                        exi,
                        pag,
                        tem,
                        aut});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void inscribirLibroAsync(int id, string tit, int exi, int pag, string tem, string aut) {
            this.inscribirLibroAsync(id, tit, exi, pag, tem, aut, null);
        }
        
        /// <remarks/>
        public void inscribirLibroAsync(int id, string tit, int exi, int pag, string tem, string aut, object userState) {
            if ((this.inscribirLibroOperationCompleted == null)) {
                this.inscribirLibroOperationCompleted = new System.Threading.SendOrPostCallback(this.OninscribirLibroOperationCompleted);
            }
            this.InvokeAsync("inscribirLibro", new object[] {
                        id,
                        tit,
                        exi,
                        pag,
                        tem,
                        aut}, this.inscribirLibroOperationCompleted, userState);
        }
        
        private void OninscribirLibroOperationCompleted(object arg) {
            if ((this.inscribirLibroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.inscribirLibroCompleted(this, new inscribirLibroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WS_WHB/registrarCliente", RequestNamespace="http://localhost/WS_WHB", ResponseNamespace="http://localhost/WS_WHB", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool registrarCliente(int car, string nom, int dpi, string dir, int tel) {
            object[] results = this.Invoke("registrarCliente", new object[] {
                        car,
                        nom,
                        dpi,
                        dir,
                        tel});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void registrarClienteAsync(int car, string nom, int dpi, string dir, int tel) {
            this.registrarClienteAsync(car, nom, dpi, dir, tel, null);
        }
        
        /// <remarks/>
        public void registrarClienteAsync(int car, string nom, int dpi, string dir, int tel, object userState) {
            if ((this.registrarClienteOperationCompleted == null)) {
                this.registrarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarClienteOperationCompleted);
            }
            this.InvokeAsync("registrarCliente", new object[] {
                        car,
                        nom,
                        dpi,
                        dir,
                        tel}, this.registrarClienteOperationCompleted, userState);
        }
        
        private void OnregistrarClienteOperationCompleted(object arg) {
            if ((this.registrarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarClienteCompleted(this, new registrarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WS_WHB/llenarConsultarLibros", RequestNamespace="http://localhost/WS_WHB", ResponseNamespace="http://localhost/WS_WHB", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet llenarConsultarLibros() {
            object[] results = this.Invoke("llenarConsultarLibros", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void llenarConsultarLibrosAsync() {
            this.llenarConsultarLibrosAsync(null);
        }
        
        /// <remarks/>
        public void llenarConsultarLibrosAsync(object userState) {
            if ((this.llenarConsultarLibrosOperationCompleted == null)) {
                this.llenarConsultarLibrosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnllenarConsultarLibrosOperationCompleted);
            }
            this.InvokeAsync("llenarConsultarLibros", new object[0], this.llenarConsultarLibrosOperationCompleted, userState);
        }
        
        private void OnllenarConsultarLibrosOperationCompleted(object arg) {
            if ((this.llenarConsultarLibrosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.llenarConsultarLibrosCompleted(this, new llenarConsultarLibrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WS_WHB/llenarPrestarLibro", RequestNamespace="http://localhost/WS_WHB", ResponseNamespace="http://localhost/WS_WHB", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet llenarPrestarLibro() {
            object[] results = this.Invoke("llenarPrestarLibro", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void llenarPrestarLibroAsync() {
            this.llenarPrestarLibroAsync(null);
        }
        
        /// <remarks/>
        public void llenarPrestarLibroAsync(object userState) {
            if ((this.llenarPrestarLibroOperationCompleted == null)) {
                this.llenarPrestarLibroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnllenarPrestarLibroOperationCompleted);
            }
            this.InvokeAsync("llenarPrestarLibro", new object[0], this.llenarPrestarLibroOperationCompleted, userState);
        }
        
        private void OnllenarPrestarLibroOperationCompleted(object arg) {
            if ((this.llenarPrestarLibroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.llenarPrestarLibroCompleted(this, new llenarPrestarLibroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WS_WHB/llenarReporte", RequestNamespace="http://localhost/WS_WHB", ResponseNamespace="http://localhost/WS_WHB", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet llenarReporte() {
            object[] results = this.Invoke("llenarReporte", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void llenarReporteAsync() {
            this.llenarReporteAsync(null);
        }
        
        /// <remarks/>
        public void llenarReporteAsync(object userState) {
            if ((this.llenarReporteOperationCompleted == null)) {
                this.llenarReporteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnllenarReporteOperationCompleted);
            }
            this.InvokeAsync("llenarReporte", new object[0], this.llenarReporteOperationCompleted, userState);
        }
        
        private void OnllenarReporteOperationCompleted(object arg) {
            if ((this.llenarReporteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.llenarReporteCompleted(this, new llenarReporteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WS_WHB/librosPrestadosSinDevolver", RequestNamespace="http://localhost/WS_WHB", ResponseNamespace="http://localhost/WS_WHB", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int librosPrestadosSinDevolver(int carne) {
            object[] results = this.Invoke("librosPrestadosSinDevolver", new object[] {
                        carne});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void librosPrestadosSinDevolverAsync(int carne) {
            this.librosPrestadosSinDevolverAsync(carne, null);
        }
        
        /// <remarks/>
        public void librosPrestadosSinDevolverAsync(int carne, object userState) {
            if ((this.librosPrestadosSinDevolverOperationCompleted == null)) {
                this.librosPrestadosSinDevolverOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlibrosPrestadosSinDevolverOperationCompleted);
            }
            this.InvokeAsync("librosPrestadosSinDevolver", new object[] {
                        carne}, this.librosPrestadosSinDevolverOperationCompleted, userState);
        }
        
        private void OnlibrosPrestadosSinDevolverOperationCompleted(object arg) {
            if ((this.librosPrestadosSinDevolverCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.librosPrestadosSinDevolverCompleted(this, new librosPrestadosSinDevolverCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WS_WHB/clienteExiste", RequestNamespace="http://localhost/WS_WHB", ResponseNamespace="http://localhost/WS_WHB", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool clienteExiste(int carne) {
            object[] results = this.Invoke("clienteExiste", new object[] {
                        carne});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void clienteExisteAsync(int carne) {
            this.clienteExisteAsync(carne, null);
        }
        
        /// <remarks/>
        public void clienteExisteAsync(int carne, object userState) {
            if ((this.clienteExisteOperationCompleted == null)) {
                this.clienteExisteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnclienteExisteOperationCompleted);
            }
            this.InvokeAsync("clienteExiste", new object[] {
                        carne}, this.clienteExisteOperationCompleted, userState);
        }
        
        private void OnclienteExisteOperationCompleted(object arg) {
            if ((this.clienteExisteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.clienteExisteCompleted(this, new clienteExisteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WS_WHB/yaPrestoElLibro", RequestNamespace="http://localhost/WS_WHB", ResponseNamespace="http://localhost/WS_WHB", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool yaPrestoElLibro(int car, int lib) {
            object[] results = this.Invoke("yaPrestoElLibro", new object[] {
                        car,
                        lib});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void yaPrestoElLibroAsync(int car, int lib) {
            this.yaPrestoElLibroAsync(car, lib, null);
        }
        
        /// <remarks/>
        public void yaPrestoElLibroAsync(int car, int lib, object userState) {
            if ((this.yaPrestoElLibroOperationCompleted == null)) {
                this.yaPrestoElLibroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnyaPrestoElLibroOperationCompleted);
            }
            this.InvokeAsync("yaPrestoElLibro", new object[] {
                        car,
                        lib}, this.yaPrestoElLibroOperationCompleted, userState);
        }
        
        private void OnyaPrestoElLibroOperationCompleted(object arg) {
            if ((this.yaPrestoElLibroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.yaPrestoElLibroCompleted(this, new yaPrestoElLibroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WS_WHB/yaReservoElLibro", RequestNamespace="http://localhost/WS_WHB", ResponseNamespace="http://localhost/WS_WHB", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool yaReservoElLibro(int car, int lib) {
            object[] results = this.Invoke("yaReservoElLibro", new object[] {
                        car,
                        lib});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void yaReservoElLibroAsync(int car, int lib) {
            this.yaReservoElLibroAsync(car, lib, null);
        }
        
        /// <remarks/>
        public void yaReservoElLibroAsync(int car, int lib, object userState) {
            if ((this.yaReservoElLibroOperationCompleted == null)) {
                this.yaReservoElLibroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnyaReservoElLibroOperationCompleted);
            }
            this.InvokeAsync("yaReservoElLibro", new object[] {
                        car,
                        lib}, this.yaReservoElLibroOperationCompleted, userState);
        }
        
        private void OnyaReservoElLibroOperationCompleted(object arg) {
            if ((this.yaReservoElLibroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.yaReservoElLibroCompleted(this, new yaReservoElLibroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WS_WHB/guardarPrestamo", RequestNamespace="http://localhost/WS_WHB", ResponseNamespace="http://localhost/WS_WHB", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool guardarPrestamo(int car, int lib) {
            object[] results = this.Invoke("guardarPrestamo", new object[] {
                        car,
                        lib});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void guardarPrestamoAsync(int car, int lib) {
            this.guardarPrestamoAsync(car, lib, null);
        }
        
        /// <remarks/>
        public void guardarPrestamoAsync(int car, int lib, object userState) {
            if ((this.guardarPrestamoOperationCompleted == null)) {
                this.guardarPrestamoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarPrestamoOperationCompleted);
            }
            this.InvokeAsync("guardarPrestamo", new object[] {
                        car,
                        lib}, this.guardarPrestamoOperationCompleted, userState);
        }
        
        private void OnguardarPrestamoOperationCompleted(object arg) {
            if ((this.guardarPrestamoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarPrestamoCompleted(this, new guardarPrestamoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WS_WHB/guardarReserva", RequestNamespace="http://localhost/WS_WHB", ResponseNamespace="http://localhost/WS_WHB", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool guardarReserva(int car, int lib) {
            object[] results = this.Invoke("guardarReserva", new object[] {
                        car,
                        lib});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void guardarReservaAsync(int car, int lib) {
            this.guardarReservaAsync(car, lib, null);
        }
        
        /// <remarks/>
        public void guardarReservaAsync(int car, int lib, object userState) {
            if ((this.guardarReservaOperationCompleted == null)) {
                this.guardarReservaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarReservaOperationCompleted);
            }
            this.InvokeAsync("guardarReserva", new object[] {
                        car,
                        lib}, this.guardarReservaOperationCompleted, userState);
        }
        
        private void OnguardarReservaOperationCompleted(object arg) {
            if ((this.guardarReservaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarReservaCompleted(this, new guardarReservaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WS_WHB/ejempleresDisponibles", RequestNamespace="http://localhost/WS_WHB", ResponseNamespace="http://localhost/WS_WHB", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ejempleresDisponibles(int lib) {
            object[] results = this.Invoke("ejempleresDisponibles", new object[] {
                        lib});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ejempleresDisponiblesAsync(int lib) {
            this.ejempleresDisponiblesAsync(lib, null);
        }
        
        /// <remarks/>
        public void ejempleresDisponiblesAsync(int lib, object userState) {
            if ((this.ejempleresDisponiblesOperationCompleted == null)) {
                this.ejempleresDisponiblesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnejempleresDisponiblesOperationCompleted);
            }
            this.InvokeAsync("ejempleresDisponibles", new object[] {
                        lib}, this.ejempleresDisponiblesOperationCompleted, userState);
        }
        
        private void OnejempleresDisponiblesOperationCompleted(object arg) {
            if ((this.ejempleresDisponiblesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ejempleresDisponiblesCompleted(this, new ejempleresDisponiblesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WS_WHB/devolver", RequestNamespace="http://localhost/WS_WHB", ResponseNamespace="http://localhost/WS_WHB", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool devolver(int car, int lib) {
            object[] results = this.Invoke("devolver", new object[] {
                        car,
                        lib});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void devolverAsync(int car, int lib) {
            this.devolverAsync(car, lib, null);
        }
        
        /// <remarks/>
        public void devolverAsync(int car, int lib, object userState) {
            if ((this.devolverOperationCompleted == null)) {
                this.devolverOperationCompleted = new System.Threading.SendOrPostCallback(this.OndevolverOperationCompleted);
            }
            this.InvokeAsync("devolver", new object[] {
                        car,
                        lib}, this.devolverOperationCompleted, userState);
        }
        
        private void OndevolverOperationCompleted(object arg) {
            if ((this.devolverCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.devolverCompleted(this, new devolverCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void inscribirLibroCompletedEventHandler(object sender, inscribirLibroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class inscribirLibroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal inscribirLibroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void registrarClienteCompletedEventHandler(object sender, registrarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registrarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registrarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void llenarConsultarLibrosCompletedEventHandler(object sender, llenarConsultarLibrosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class llenarConsultarLibrosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal llenarConsultarLibrosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void llenarPrestarLibroCompletedEventHandler(object sender, llenarPrestarLibroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class llenarPrestarLibroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal llenarPrestarLibroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void llenarReporteCompletedEventHandler(object sender, llenarReporteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class llenarReporteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal llenarReporteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void librosPrestadosSinDevolverCompletedEventHandler(object sender, librosPrestadosSinDevolverCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class librosPrestadosSinDevolverCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal librosPrestadosSinDevolverCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void clienteExisteCompletedEventHandler(object sender, clienteExisteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class clienteExisteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal clienteExisteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void yaPrestoElLibroCompletedEventHandler(object sender, yaPrestoElLibroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class yaPrestoElLibroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal yaPrestoElLibroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void yaReservoElLibroCompletedEventHandler(object sender, yaReservoElLibroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class yaReservoElLibroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal yaReservoElLibroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void guardarPrestamoCompletedEventHandler(object sender, guardarPrestamoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guardarPrestamoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guardarPrestamoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void guardarReservaCompletedEventHandler(object sender, guardarReservaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guardarReservaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guardarReservaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ejempleresDisponiblesCompletedEventHandler(object sender, ejempleresDisponiblesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ejempleresDisponiblesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ejempleresDisponiblesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void devolverCompletedEventHandler(object sender, devolverCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class devolverCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal devolverCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591