CREATE DATABASE QuetzalExpress
GO
USE QuetzalExpress
GO
CREATE TABLE SOLICITUD (
	id INT IDENTITY(1,1),
	nombre VARCHAR(45) NOT NULL,
	apellido VARCHAR(45) NOT NULL,
	nit VARCHAR(20) NULL,
	telefono INT NULL,
	domicilio VARCHAR(45) NULL,
	sucursal VARCHAR(45) NULL,
	tarjeta VARCHAR(20) NOT NULL,
	correo VARCHAR(45) NOT NULL,
	contraseña VARCHAR(45)
)
GO
CREATE TABLE CLIENTE (
	casilla INT NOT NULL,
	solicitud INT NOT NULL,
	nombre VARCHAR(45) NOT NULL,
	apellido VARCHAR(45) NOT NULL,
	nit VARCHAR(20) NULL,
	telefono INT NULL,
	domicilio VARCHAR(45) NULL,
	sucursal VARCHAR(45) NULL,
	tarjeta VARCHAR(20) NOT NULL UNIQUE,
	correo VARCHAR(45) NOT NULL UNIQUE,
	contraseña VARCHAR(45)
)
GO
CREATE TABLE EMPLEADO (
	id INT IDENTITY(1,1),
	nombre VARCHAR(45) NOT NULL,
	apellido VARCHAR(45) NOT NULL,
	telefono VARCHAR(45) NULL,
	domicilio VARCHAR(45) NULL,
	sueldo FLOAT NOT NULL,
	sucursal VARCHAR(45)NOT NULL,
	departamento VARCHAR(45) NOT NULL,
	correo VARCHAR(45) NOT NULL,
	contraseña VARCHAR(45) NOT NULL,
	tipo VARCHAR(45) NULL
)
GO
CREATE TABLE PAQUETE (
	id INT IDENTITY(1,1),
	peso FLOAT NOT NULL,
	precio FLOAT NOT NULL,
	categoria VARCHAR(45) NOT NULL,
	casilla INT NOT NULL
)
GO
CREATE TABLE BODEGA (
	id INT IDENTITY(1,1),
	lote INT NOT NULL,
	categoria VARCHAR(45) NOT NULL,
	casilla INT NOT NULL,
	peso FLOAT NOT NULL,
	precio FLOAT NOT NULL
)
GO
CREATE TABLE LOTE (
	id INT NOT NULL
)
GO
CREATE TABLE ASIGNACION_LOTE (
	id INT IDENTITY(1,1),
	lote INT NOT NULL,
	paquete INT NOT NULL
)
GO
CREATE TABLE IMPUESTO (
	id INT IDENTITY(1,1),
	nombre VARCHAR(45) NOT NULL,
	valor FLOAT NOT NULL
)
GO
CREATE TABLE FACTURA (
	id INT IDENTITY(1,1),
	fecha DATETIME NOT NULL,
	cliente INT NOT NULL,
	empleado INT NOT NULL
)
GO
CREATE TABLE DETALLE (
	 id INT IDENTITY(1,1),
	 factura INT NOT NULL,
	 paquete INT NOT NULL,
	 total FLOAT NOT NULL
)
GO
ALTER TABLE SOLICITUD ADD PRIMARY KEY (id)
ALTER TABLE CLIENTE ADD PRIMARY KEY (casilla)
ALTER TABLE EMPLEADO ADD PRIMARY KEY (id)
ALTER TABLE PAQUETE ADD PRIMARY KEY (id)
ALTER TABLE BODEGA ADD PRIMARY KEY (id)
ALTER TABLE LOTE ADD PRIMARY KEY (id)
ALTER TABLE ASIGNACION_LOTE ADD PRIMARY KEY (id)
ALTER TABLE IMPUESTO ADD PRIMARY KEY (id)
ALTER TABLE FACTURA ADD PRIMARY KEY (id)
ALTER TABLE DETALLE ADD PRIMARY KEY (id)
GO
ALTER TABLE CLIENTE ADD FOREIGN KEY (solicitud) REFERENCES SOLICITUD (id)
ALTER TABLE PAQUETE ADD FOREIGN KEY (casilla) REFERENCES CLIENTE (casilla)
ALTER TABLE BODEGA ADD FOREIGN KEY (lote) REFERENCES LOTE (id)
ALTER TABLE BODEGA ADD FOREIGN KEY (casilla) REFERENCES CLIENTE (casilla)
ALTER TABLE ASIGNACION_LOTE ADD FOREIGN KEY (lote) REFERENCES LOTE (id)
ALTER TABLE ASIGNACION_LOTE ADD FOREIGN KEY (paquete) REFERENCES PAQUETE (id)
ALTER TABLE FACTURA ADD FOREIGN KEY (cliente) REFERENCES CLIENTE (casilla)
ALTER TABLE FACTURA ADD FOREIGN KEY (empleado) REFERENCES EMPLEADO (id)
ALTER TABLE DETALLE ADD FOREIGN KEY (factura) REFERENCES FACTURA (id)
ALTER TABLE DETALLE ADD FOREIGN KEY (paquete) REFERENCES PAQUETE (id)
GO

SELECT * FROM SOLICITUD
SELECT * FROM CLIENTE
SELECT * FROM EMPLEADO
SELECT * FROM FACTURA
SELECT * FROM PAQUETE
SELECT * FROM IMPUESTO
SELECT * FROM LOTE
SELECT * FROM ASIGNACION_LOTE
INSERT INTO SOLICITUD VALUES ('Marlon', 'Salazar', '12346', 55147899, 'Guatemala', 'Majadas', '123ABC', 'marlon@hotmail.com', '4411')
INSERT INTO SOLICITUD VALUES ('{0}', '{1}', '{2}', 3, '{4}', '{5}', '{6}', '{7}', '{8}')
INSERT INTO CLIENTE VALUES (1, 1,	'Kairi', 'Franco',	'12345'	, 30330294,	'Guatemala',	'Ninguna',	'123ABC',	'kairi@yahoo.com',	'4411')
INSERT INTO EMPLEADO VALUES ('Julio', 'Pineda', 2555888,'Guatemala', 3000.50, '01', 'Servicio al Cliente', 'em1', '4411', 'empleado')
INSERT INTO EMPLEADO VALUES ('Julio', 'Pineda', 2555888,'Guatemala', 3000.50, '01', 'Bodega', 'em2', '4411', 'empleado')
INSERT INTO EMPLEADO VALUES ('Julio', 'Pineda', 2555888,'Guatemala', 3000.50, '01', 'Registro', 'em3', '4411', 'empleado')
INSERT INTO EMPLEADO VALUES ('Julio', 'Pineda', 2555888,'Guatemala', 3000.50, '01', 'Servicio al Cliente', 'em4', '4411', 'Director')
INSERT INTO EMPLEADO VALUES ('Julio', 'Pineda', 2555888,'Guatemala', 3000.50, '01', 'nada', 'em5', '4411', 'Administrador')
INSERT INTO IMPUESTO VALUES ('Zapatos', 0.15)
INSERT INTO PAQUETE VALUES (4, 4, 'Zapatos', 1)

DELETE FROM EMPLEADO