CREATE DATABASE QuetzalExpress
GO
USE QuetzalExpress
GO
CREATE TABLE CLIENTE (
	id INT IDENTITY(1,1),
	casilla INT UNIQUE NULL,
	nombre VARCHAR(45) NOT NULL,
	apellido VARCHAR(45) NOT NULL,
	nit VARCHAR(20) NULL,
	telefono INT NULL,
	domicilio VARCHAR(45) NULL,
	sucursal VARCHAR(45) NULL,
	tarjeta VARCHAR(20) NOT NULL UNIQUE,
	correo VARCHAR(45) NOT NULL UNIQUE,
	contraseña VARCHAR(45)
)
GO
CREATE TABLE EMPLEADO (
	id INT IDENTITY(1,1),
	nombre VARCHAR(45) NOT NULL,
	apellido VARCHAR(45) NOT NULL,
	telefono VARCHAR(45) NULL,
	domicilio VARCHAR(45) NULL,
	sueldo FLOAT NOT NULL,
	sucursal VARCHAR(45)NOT NULL,
	departamento VARCHAR(45) NOT NULL
)
GO
CREATE TABLE PAQUETE (
	id INT IDENTITY(1,1),
	peso FLOAT NOT NULL,
	precio FLOAT NOT NULL,
	categoria VARCHAR(45) NOT NULL,
	casilla INT NOT NULL,
	lote INT NULL
)
GO
CREATE TABLE BODEGA (
	id INT IDENTITY(1,1),
	lote INT NOT NULL,
	categoria VARCHAR(45) NOT NULL,
	casilla INT NOT NULL,
	peso FLOAT NOT NULL,
	precio FLOAT NOT NULL
)
GO
CREATE TABLE LOTE (
	id INT NOT NULL
)
GO
CREATE TABLE IMPUESTO (
	id INT IDENTITY(1,1),
	nombre VARCHAR(45) NOT NULL,
	valor FLOAT NOT NULL
)
GO
CREATE TABLE FACTURA (
	id INT IDENTITY(1,1),
	fecha DATETIME NOT NULL,
	cliente INT NOT NULL,
	empleado INT NOT NULL
)
GO
CREATE TABLE DETALLE (
	 id INT IDENTITY(1,1),
	 factura INT NOT NULL,
	 paquete INT NOT NULL,
	 total FLOAT NOT NULL
)
GO
ALTER TABLE CLIENTE ADD PRIMARY KEY (id)
ALTER TABLE EMPLEADO ADD PRIMARY KEY (id)
ALTER TABLE PAQUETE ADD PRIMARY KEY (id)
ALTER TABLE BODEGA ADD PRIMARY KEY (id)
ALTER TABLE LOTE ADD PRIMARY KEY (id)
ALTER TABLE IMPUESTO ADD PRIMARY KEY (id)
ALTER TABLE FACTURA ADD PRIMARY KEY (id)
ALTER TABLE DETALLE ADD PRIMARY KEY (id)
GO
ALTER TABLE PAQUETE ADD FOREIGN KEY (casilla) REFERENCES CLIENTE (casilla)
ALTER TABLE PAQUETE ADD FOREIGN KEY (lote) REFERENCES CLIENTE (id)
ALTER TABLE BODEGA ADD FOREIGN KEY (lote) REFERENCES LOTE (id)
ALTER TABLE BODEGA ADD FOREIGN KEY (casilla) REFERENCES CLIENTE (casilla)
ALTER TABLE FACTURA ADD FOREIGN KEY (cliente) REFERENCES CLIENTE (casilla)
ALTER TABLE FACTURA ADD FOREIGN KEY (empleado) REFERENCES EMPLEADO (id)
ALTER TABLE DETALLE ADD FOREIGN KEY (factura) REFERENCES FACTURA (id)
ALTER TABLE DETALLE ADD FOREIGN KEY (paquete) REFERENCES PAQUETE (id)
GO

SELECT * FROM CLIENTE
INSERT INTO CLIENTE VALUES (-2, 'Marlon', 'Salazar', '12345', 55147898, 'Guatemala', 'Majadas', '789ABC', 'marlon3@hotmail.com', '4411')
