DROP DATABASE Qu3tzal3xpr3ss

CREATE DATABASE Qu3tzal3xpr3ss
GO
USE Qu3tzal3xpr3ss
GO
CREATE TABLE SOLICITUD (
	id INT IDENTITY(1,1),
	nombre VARCHAR(45) NOT NULL,
	apellido VARCHAR(45) NOT NULL,
	nit VARCHAR(20) NULL,
	telefono INT NULL,
	domicilio VARCHAR(45) NULL,
	sucursal INT NULL,
	tarjeta VARCHAR(20) NOT NULL,
	correo VARCHAR(45) NOT NULL,
	contraseña VARCHAR(45),
	estado VARCHAR(50) NOT NULL
)
GO
CREATE TABLE CLIENTE (
	casilla INT NOT NULL,
	solicitud INT NOT NULL,
	nombre VARCHAR(45) NOT NULL,
	apellido VARCHAR(45) NOT NULL,
	nit VARCHAR(20) NULL,
	telefono INT NULL,
	domicilio VARCHAR(45) NULL,
	sucursal INT NULL,
	tarjeta VARCHAR(20) NOT NULL UNIQUE,
	correo VARCHAR(45) NOT NULL UNIQUE,
	contraseña VARCHAR(45)
)
GO
CREATE TABLE EMPLEADO (
	id INT IDENTITY(1,1),
	nombre VARCHAR(45) NOT NULL,
	apellido VARCHAR(45) NOT NULL,
	telefono VARCHAR(45) NULL,
	domicilio VARCHAR(45) NULL,
	correo VARCHAR(45) NULL,
	contraseña VARCHAR(45) NULL,
	tipo VARCHAR(45) NULL,
	estado VARCHAR(50) NOT NULL
)
GO
CREATE TABLE DEPARTAMENTO(
	id INT IDENTITY(1,1),
	nombre VARCHAR(50),
	sucursal INT NOT NULL
)
GO
CREATE TABLE SUCURSAL(
	id INT IDENTITY(1,1),
	nombre VARCHAR(50)
)
GO
CREATE TABLE ASIGNACION_DEPARTAMENTO(
	id INT IDENTITY(1,1),
	empleado INT NOT NULL,
	departamento INT NOT NULL,
	fecha DATETIME NOT NULL,
	sueldo FLOAT NOT NULL
)
GO
CREATE TABLE PAQUETE (
	id INT IDENTITY(1,1),
	peso FLOAT NOT NULL,
	precio FLOAT NULL,
	categoria INT NOT NULL,
	casilla INT NOT NULL,
	imagen VARCHAR(250) NULL,
	estado VARCHAR(50) NULL
)
GO
CREATE TABLE ESTADO (
	id INT IDENTITY(1,1),
	paquete INT NOT NULL,
	fecha DATETIME NOT NULL,
	nombre VARCHAR(45) NOT NULL	
)
GO
CREATE TABLE BODEGA (
	id INT IDENTITY(1,1),
	lote INT NULL,
	categoria VARCHAR(45) NULL,
	casilla INT NULL,
	peso FLOAT NULL,
	precio FLOAT NULL,
	estado VARCHAR(45) NULL
)
GO
CREATE TABLE LOTE (
	id INT NOT NULL,
	fecha_salida DATETIME NOT NULL
)
GO
CREATE TABLE ASIGNACION_LOTE (
	id INT IDENTITY(1,1),
	lote INT NOT NULL,
	paquete INT NOT NULL
)
GO
CREATE TABLE IMPUESTO (
	id INT IDENTITY(1,1),
	nombre VARCHAR(45) NOT NULL,
	valor FLOAT NOT NULL
)
GO
CREATE TABLE COBRO (
	id INT IDENTITY(1,1),
	nombre VARCHAR(45) NOT NULL,
	valor FLOAT(45) NOT NULL,
	estado VARCHAR(45) NOT NULL,
)
GO
CREATE TABLE FACTURA (
	id INT IDENTITY(1,1),
	fecha DATETIME NOT NULL,
	cliente INT NOT NULL,
	empleado INT NOT NULL,
	paquete INT NOT NULL,
	total FLOAT NOT NULL
)
GO

ALTER TABLE SOLICITUD ADD PRIMARY KEY (id)
ALTER TABLE CLIENTE ADD PRIMARY KEY (casilla)
ALTER TABLE EMPLEADO ADD PRIMARY KEY (id)
ALTER TABLE DEPARTAMENTO ADD PRIMARY KEY (id)
ALTER TABLE SUCURSAL ADD PRIMARY KEY (id)
ALTER TABLE ASIGNACION_DEPARTAMENTO ADD PRIMARY KEY (id)
ALTER TABLE PAQUETE ADD PRIMARY KEY (id)
ALTER TABLE ESTADO ADD PRIMARY KEY (id)
ALTER TABLE BODEGA ADD PRIMARY KEY (id)
ALTER TABLE LOTE ADD PRIMARY KEY (id)
ALTER TABLE ASIGNACION_LOTE ADD PRIMARY KEY (id)
ALTER TABLE IMPUESTO ADD PRIMARY KEY (id)
ALTER TABLE COBRO ADD PRIMARY KEY (id)
ALTER TABLE FACTURA ADD PRIMARY KEY (id)
GO
ALTER TABLE CLIENTE ADD FOREIGN KEY (solicitud) REFERENCES SOLICITUD (id)
ALTER TABLE CLIENTE ADD FOREIGN KEY (sucursal) REFERENCES SUCURSAL (id)
ALTER TABLE DEPARTAMENTO ADD FOREIGN KEY (sucursal) REFERENCES SUCURSAL (id)
ALTER TABLE ASIGNACION_DEPARTAMENTO ADD FOREIGN KEY (empleado) REFERENCES EMPLEADO (id)
ALTER TABLE ASIGNACION_DEPARTAMENTO ADD FOREIGN KEY (departamento) REFERENCES DEPARTAMENTO (id)
ALTER TABLE PAQUETE ADD FOREIGN KEY (casilla) REFERENCES CLIENTE (casilla)
ALTER TABLE PAQUETE ADD FOREIGN KEY (categoria) REFERENCES IMPUESTO (id)
ALTER TABLE ESTADO ADD FOREIGN KEY (paquete) REFERENCES PAQUETE (id)
ALTER TABLE BODEGA ADD FOREIGN KEY (lote) REFERENCES LOTE (id)
ALTER TABLE BODEGA ADD FOREIGN KEY (casilla) REFERENCES CLIENTE (casilla)
ALTER TABLE ASIGNACION_LOTE ADD FOREIGN KEY (lote) REFERENCES LOTE (id)
ALTER TABLE ASIGNACION_LOTE ADD FOREIGN KEY (paquete) REFERENCES PAQUETE (id)
ALTER TABLE FACTURA ADD FOREIGN KEY (cliente) REFERENCES CLIENTE (casilla)
ALTER TABLE FACTURA ADD FOREIGN KEY (empleado) REFERENCES EMPLEADO (id)
ALTER TABLE FACTURA ADD FOREIGN KEY (paquete) REFERENCES paquete (id)
GO

INSERT INTO SUCURSAL VALUES ('Miami FL')
INSERT INTO SUCURSAL VALUES ('Guatemala')
INSERT INTO DEPARTAMENTO VALUES ('Registro', 1)
/*INSERT INTO DEPARTAMENTO VALUES ('Servicio al Cliente', 1)
INSERT INTO DEPARTAMENTO VALUES ('Bodega', 1)
INSERT INTO DEPARTAMENTO VALUES ('Registro', 2)*/
INSERT INTO DEPARTAMENTO VALUES ('Servicio al Cliente', 2)
INSERT INTO DEPARTAMENTO VALUES ('Bodega', 2)
INSERT INTO COBRO VALUES ('Libra', 5, 'habilitado')
INSERT INTO COBRO VALUES ('Comision', 0.05, 'habilitado')

SELECT * FROM SOLICITUD
SELECT * FROM CLIENTE
SELECT * FROM EMPLEADO
SELECT * FROM DEPARTAMENTO
SELECT * FROM SUCURSAL
SELECT * FROM ASIGNACION_DEPARTAMENTO
SELECT * FROM FACTURA
SELECT * FROM IMPUESTO
SELECT * FROM PAQUETE
SELECT * FROM IMPUESTO
SELECT * FROM LOTE
SELECT * FROM ASIGNACION_LOTE
SELECT * FROM ESTADO
SELECT * FROM COBRO
SELECT * FROM BODEGA

INSERT INTO EMPLEADO VALUES ('Julio', 'Pineda', 24401010,'EEUU', 'em1', '4411', 'empleado', 'contratado')
INSERT INTO ASIGNACION_DEPARTAMENTO VALUES ((SELECT MAX(id) FROM EMPLEADO), (SELECT id FROM DEPARTAMENTO WHERE nombre = 'Registro' AND sucursal = (SELECT id FROM SUCURSAL WHERE nombre = 'Miami FL')), (SELECT GETDATE()), 2800)
INSERT INTO EMPLEADO VALUES ('Mario', 'Campos', 24578984,'Guatemala', 'em2', '4411', 'empleado', 'contratado')
INSERT INTO ASIGNACION_DEPARTAMENTO VALUES ((SELECT MAX(id) FROM EMPLEADO), (SELECT id FROM DEPARTAMENTO WHERE nombre = 'Bodega' AND sucursal = (SELECT id FROM SUCURSAL WHERE nombre = 'Guatemala')), (SELECT GETDATE()), 3100)
INSERT INTO EMPLEADO VALUES ('Lisa', 'Herrera', 30257896,'Guatemala', 'em3', '4411', 'empleado', 'contratado')
INSERT INTO ASIGNACION_DEPARTAMENTO VALUES ((SELECT MAX(id) FROM EMPLEADO), (SELECT id FROM DEPARTAMENTO WHERE nombre = 'Servicio al Cliente' AND sucursal = (SELECT id FROM SUCURSAL WHERE nombre = 'Guatemala')), (SELECT GETDATE()), 2800)
INSERT INTO EMPLEADO VALUES ('Esteban', 'Andrade', 55147896,'EEUU', 'em4', '4411', 'director', 'contratado')
INSERT INTO ASIGNACION_DEPARTAMENTO VALUES ((SELECT MAX(id) FROM EMPLEADO), (SELECT id FROM DEPARTAMENTO WHERE nombre = 'Registro' AND sucursal = (SELECT id FROM SUCURSAL WHERE nombre = 'Miami FL')), (SELECT GETDATE()), 5000)
INSERT INTO EMPLEADO VALUES ('Noe', 'Rivera', 33669988,'Guatemala', 'em5', '4411', 'director', 'contratado')
INSERT INTO ASIGNACION_DEPARTAMENTO VALUES ((SELECT MAX(id) FROM EMPLEADO), (SELECT id FROM DEPARTAMENTO WHERE nombre = 'Bodega' AND sucursal = (SELECT id FROM SUCURSAL WHERE nombre = 'Guatemala')), (SELECT GETDATE()), 6000)
INSERT INTO EMPLEADO VALUES ('Wilson', 'Mux', 30254777,'Guatemala', 'em6', '4411', 'administrador', 'contratado')
INSERT INTO ASIGNACION_DEPARTAMENTO VALUES ((SELECT MAX(id) FROM EMPLEADO), (SELECT id FROM DEPARTAMENTO WHERE nombre = 'Registro' AND sucursal = (SELECT id FROM SUCURSAL WHERE nombre = 'Miami FL')), (SELECT GETDATE()), 8000)

SELECT emp.nombre, emp.tipo, (SELECT DEPARTAMENTO.nombre FROM DEPARTAMENTO WHERE asigdep.departamento = DEPARTAMENTO.id) FROM EMPLEADO emp, ASIGNACION_DEPARTAMENTO asigdep WHERE asigdep.empleado = emp.id
SELECT id, imagen FROM PAQUETE WHERE imagen != NULL AND estado = 'pendiente'
SELECT emp.id AS 'ID', emp.nombre AS 'Nombre', emp.apellido AS 'Apellido', (SELECT sueldo FROM ASIGNACION_DEPARTAMENTO WHERE empleado = emp.id) AS 'Sueldo', (SELECT ad.departamento FROM ASIGNACION_DEPARTAMENTO WHERE empleado = emp.id) AS 'Departamento' FROM EMPLEADO emp, ASIGNACION_DEPARTAMENTO ad WHERE ad.departamento = '{0}' AND tipo != 'director'

INSERT INTO IMPUESTO VALUES ('Zapatos', 0.15)
INSERT INTO IMPUESTO VALUES ('CD', 0.10)
INSERT INTO IMPUESTO VALUES ('Cinta impresora', 0.15)
INSERT INTO IMPUESTO VALUES ('Electrónicos', 0.25)
INSERT INTO IMPUESTO VALUES ('Papeleria', 6%)

SELECT nombre FROM ESTADO WHERE paquete = 5 ORDER BY fecha DESC
SELECT PAQUETE.id AS 'ID', PAQUETE.categoria AS 'Categoría', (SELECT MAX(fecha) FROM ESTADO WHERE) AS 'Fecha de cambio', (SELECT ESTADO.nombre FROM ESTADO WHERE ESTADO.fecha = MAX(ESTADO.fecha)) AS 'Estado' FROM PAQUETE, ESTADO WHERE PAQUETE.casilla = 1
SELECT paquete, fecha FROM ESTADO, PAQUETE WHERE casilla = 1 GROUP BY fecha


DELETE FROM IMPUESTO WHERE nombre = 'Cinta impresora'
DELETE FROM EMPLEADO
DELETE FROM DEPARTAMENTO
DELETE FROM PAQUETE
DELETE FROM ESTADO
DELETE FROM ASIGNACION_LOTE
DELETE FROM BODEGA
DELETE FROM FACTURA
DELETE FROM IMPUESTO

BULK INSERT IMPUESTO FROM 'C:\Users\ITZMARWIN7\Desktop\Fase 3\WebSites\QuetzalExpress\csv\Impuestos.txt' WITH (FIELDTERMINATOR = ',', ROWTERMINATOR = '\n')


SELECT PAQUETE.id AS 'ID', (SELECT IMPUESTO.nombre FROM IMPUESTO, PAQUETE p WHERE IMPUESTO.id = p.categoria AND PAQUETE.casilla = 1) AS 'Categoría' FROM PAQUETE WHERE casilla = 1
SELECT IMPUESTO.nombre FROM IMPUESTO, PAQUETE p WHERE IMPUESTO.id = p.categoria
SELECT ESTADO.nombre, PAQUETE.precio, PAQUETE.peso, (SELECT IMPUESTO.nombre FROM IMPUESTO WHERE IMPUESTO.id = PAQUETE.categoria) FROM ESTADO, PAQUETE WHERE fecha = (SELECT MAX(ESTADO.fecha) FROM ESTADO WHERE ESTADO.paquete = 2) AND PAQUETE.id = 2

SELECT (SELECT imp.nombre FROM IMPUESTO imp WHERE imp.id = paq.categoria) AS 'Categoria', (SELECT COUNT(est.paquete) FROM ESTADO est WHERE est.paquete = paq.id AND est.nombre = 'Recibido') AS 'Paquetes recibidos', (SELECT COUNT(est.paquete) FROM ESTADO est WHERE est.paquete = paq.id AND est.nombre = 'Perdido') AS 'Paquetes perdidos', (SELECT COUNT(est.paquete) FROM ESTADO est WHERE est.paquete = paq.id AND est.nombre = 'Entregado') AS 'Paquetes entregados' FROM PAQUETE paq, IMPUESTO imp WHERE paq.categoria = imp.id
SELECT (SUM(paq.precio))*(SELECT imp.valor FROM IMPUESTO imp) FROM PAQUETE paq, IMPUESTO imp WHERE paq.categoria = imp.id





SELECT (SELECT imp.nombre FROM IMPUESTO imp WHERE imp.id = paq.categoria) AS 'Categoria', (SELECT COUNT(est.paquete) FROM ESTADO est WHERE est.paquete = paq.id AND est.nombre = 'Recibido') AS 'Paquetes recibidos', (SELECT COUNT(est.paquete) FROM ESTADO est WHERE est.paquete = paq.id AND est.nombre = 'Perdido') AS 'Paquetes perdidos', (SELECT COUNT(est.paquete) FROM ESTADO est WHERE est.paquete = paq.id AND est.nombre = 'Entregado') AS 'Paquetes entregados' FROM PAQUETE paq, IMPUESTO imp WHERE paq.categoria = imp.id
SELECT (SELECT valor FROM IMPUESTO WHERE id = paq.categoria)*SUM(paq.precio) AS 'Suma de impuestos', (SELECT valor FROM COBRO WHERE nombre = 'Libra')*SUM(paq.peso) AS 'Suma de pesos' FROM PAQUETE paq GROUP BY paq.categoria

SELECT * FROM PAQUETE
SELECT * FROM IMPUESTO


SELECT empleado AS 'Empleado', sueldo AS 'Sueldo', departamento AS 'Departamento', MAX(fecha) AS 'Fecha de modificación' FROM ASIGNACION_DEPARTAMENTO WHERE empleado = 6 GROUP BY empleado, sueldo, departamento
SELECT * FROM ASIGNACION_DEPARTAMENTO



SELECT emp.id AS 'ID', emp.nombre AS 'Nombre', emp.apellido AS 'Apellido', (SELECT sueldo FROM ASIGNACION_DEPARTAMENTO WHERE empleado = emp.id) AS 'Sueldo', (SELECT nombre FROM DEPARTAMENTO WHERE id = (SELECT ad.departamento FROM ASIGNACION_DEPARTAMENTO WHERE empleado = emp.id)) AS 'Departamento' FROM EMPLEADO emp, ASIGNACION_DEPARTAMENTO ad WHERE emp.id = ad.empleado AND (SELECT nombre FROM DEPARTAMENTO WHERE id =  ad.departamento) = 'Registro' AND tipo = 'empleado'