CREATE DATABASE HardBooks
USE HardBooks

CREATE TABLE CLIENTE (
	carne INT NOT NULL,
	nombre VARCHAR(50) NOT NULL,
	dpi INT NOT NULL,
	direccion VARCHAR(100) NOT NULL,
	telefono INT NOT NULL
)
CREATE TABLE LIBRO (
	id INT NOT NULL,
	titulo VARCHAR(50) NOT NULL,
	existencias INT NOT NULL,
	paginas INT NOT NULL,
	tema VARCHAR(50) NOT NULL,
	autor VARCHAR(50) NOT NULL
)
CREATE TABLE PRESTAMO (
	id INT NOT NULL IDENTITY (1,1),
	fecha_prestamo DATETIME NOT NULL,
	fecha_devolucion DATETIME NULL,
	cliente INT NOT NULL,
	libro INT NOT NULL,
)
CREATE TABLE RESERVA (
	id INT NOT NULL IDENTITY (1,1),
	fecha_reserva DATETIME NOT NULL,
	cliente INT NOT NULL,
	libro INT NOT NULL,
)
GO
ALTER TABLE CLIENTE ADD PRIMARY KEY (carne)
ALTER TABLE LIBRO ADD PRIMARY KEY (id)
ALTER TABLE PRESTAMO ADD PRIMARY KEY (id)
ALTER TABLE RESERVA ADD PRIMARY KEY (id)
GO
ALTER TABLE PRESTAMO ADD FOREIGN KEY (cliente) REFERENCES CLIENTE (carne)
ALTER TABLE PRESTAMO ADD FOREIGN KEY (libro) REFERENCES LIBRO (id)
ALTER TABLE RESERVA ADD FOREIGN KEY (cliente) REFERENCES CLIENTE (carne)
ALTER TABLE RESERVA ADD FOREIGN KEY (libro) REFERENCES LIBRO (id)
GO
